{% set version = '0.3.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-messydates
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/messydates_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/messydates/messydates_{{ version }}.tar.gz
  sha256: ca726a71e3a4958e275d48dd039a78239006a18f4788777f8efb22bc953810c7

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-dplyr
    - r-lubridate
    - r-purrr
    - r-stringr
    - r-tibble

  run:
    - r-base
    - r-dplyr
    - r-lubridate
    - r-purrr
    - r-stringr
    - r-tibble

test:
  commands:
    - $R -e "library('messydates')"           # [not win]
    - "\"%R%\" -e \"library('messydates')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=messydates
  license: MIT
  summary: Contains a set of tools for constructing and coercing into and from the "mdate" class.
    This date class implements ISO 8601-2:2019(E) and allows regular dates to be annotated
    to express unspecified date components, approximate or uncertain date components,
    date ranges, and sets of dates. This is useful for describing and analysing temporal
    information, whether historical or recent, where date precision may vary.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
    recipe-maintainers:
      - conda-forge/r
      - thewchan

# The original CRAN metadata for this package was:

# Package: messydates
# Title: A Flexible Class for Messy Dates
# Description: Contains a set of tools for constructing and coercing into and from the "mdate" class. This date class implements ISO 8601-2:2019(E) and allows regular dates to be annotated to express unspecified date components, approximate or uncertain date components, date ranges, and sets of dates. This is useful for describing and analysing temporal information, whether historical or recent, where date precision may vary.
# Version: 0.3.5
# Date: 2023-01-20
# Authors@R: c(person(given = "James", family = "Hollway", role = c("cre", "aut", "ctb"), email = "james.hollway@graduateinstitute.ch", comment = c("IHEID", ORCID = "0000-0002-8361-9647")), person(given = "Henrique", family = "Sposito", role = "ctb", comment = c("IHEID", ORCID = "0000-0003-3420-6085")), person(given = "Jael", family = "Tan", role = "ctb", comment = c("IHEID", ORCID = "0000-0002-6234-9764")))
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# LazyData: true
# VignetteBuilder: knitr
# Imports: stringr, purrr, lubridate, tibble, dplyr
# Suggests: testthat (>= 3.0.0), covr, rmarkdown, knitr
# Config/testthat/edition: 3
# Depends: R (>= 3.4)
# NeedsCompilation: no
# Packaged: 2023-01-20 13:20:12 UTC; henriquesposito
# Author: James Hollway [cre, aut, ctb] (IHEID, <https://orcid.org/0000-0002-8361-9647>), Henrique Sposito [ctb] (IHEID, <https://orcid.org/0000-0003-3420-6085>), Jael Tan [ctb] (IHEID, <https://orcid.org/0000-0002-6234-9764>)
# Maintainer: James Hollway <james.hollway@graduateinstitute.ch>
# Repository: CRAN
# Date/Publication: 2023-01-20 17:40:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
